### ISSUE TITLE
won't install or build bdist_wheel

### ISSUE THREAD

**Issue by prjemian** [prjemian/blnuhr#1]
```
(base) mintadmin@mint-vm:~$ pip install blnuhr
Collecting blnuhr
  Using cached https://files.pythonhosted.org/packages/22/02/fa08d765be7f040506230d68e5b4184ddcdee35f960bbf00475f16306617/blnuhr-0.1.12.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6rs0sxo7/blnuhr/setup.py", line 15, in <module>
        import blnuhr
      File "src/blnuhr/__init__.py", line 2, in <module>
        from main import *
    ModuleNotFoundError: No module named 'main'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6rs0sxo7/blnuhr/


(base) mintadmin@mint-vm:~/.../eclipse/blnuhr$ pip install -e .
Obtaining file:///home/mintadmin/Documents/eclipse/blnuhr
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mintadmin/Documents/eclipse/blnuhr/setup.py", line 15, in <module>
        import blnuhr
      File "src/blnuhr/__init__.py", line 2, in <module>
        from main import *
    ModuleNotFoundError: No module named 'main'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/mintadmin/Documents/eclipse/blnuhr/


(base) mintadmin@mint-vm:~/.../eclipse/blnuhr$ python ./setup.py bdist_wheel
Traceback (most recent call last):
  File "./setup.py", line 15, in <module>
    import blnuhr
  File "src/blnuhr/__init__.py", line 2, in <module>
    from main import *
ModuleNotFoundError: No module named 'main'
```

**Comment by prjemian** [comment]
These are symptoms of bit-rot now that python3 is used.  Time to refactor.
